### ISSUE TITLE
Change the Academics and Administration...

### ISSUE THREAD

**Issue by ToniWarren** [suncoast-devs/gateway#4]
columns to be in order of the process of the interviews. Add the Scheduled Interviews then Administration, then Academics, then a Sent Acceptance column. Can this be automated from Nutshell?

**Comment by ambethia** [comment]
I will open an additional Issue for automation from Nutshell.

**Comment by ambethia** [comment]
Closed in 47df588 

@ToniWarren I also added a column for "Application Complete" to the home screen and unhid them from the list. This change might help with keeping those potential leads from dropping through the cracks so you can find them in Nutshell via Gateway.
